import React from 'react';
import type { Feature } from '../../types.ts';
import { RAW_FEATURES } from '../../constants.tsx';
import { lazyWithRetry } from '../../services/componentLoader.ts';

const componentMap: Record<string, React.FC<any>> = {
    'ai-command-center': lazyWithRetry(() => import('@/components/features/AiCommandCenter.tsx'), 'AiCommandCenter'),
    'project-explorer': lazyWithRetry(() => import('@/components/features/ProjectExplorer.tsx'), 'ProjectExplorer'),
    'workspace-connector-hub': lazyWithRetry(() => import('@/components/features/WorkspaceConnectorHub.tsx'), 'WorkspaceConnectorHub'),
    'ai-code-explainer': lazyWithRetry(() => import('@/components/AiCodeExplainer.tsx'), 'AiCodeExplainer'),
    'ai-feature-builder': lazyWithRetry(() => import('@/components/features/AiFeatureBuilder.tsx'), 'AiFeatureBuilder'),
    'regex-sandbox': lazyWithRetry(() => import('@/components/features/RegexSandbox.tsx'), 'RegexSandbox'),
    'portable-snippet-vault': lazyWithRetry(() => import('@/components/features/SnippetVault.tsx'), 'SnippetVault'),
    'css-grid-editor': lazyWithRetry(() => import('@/components/features/CssGridEditor.tsx'), 'CssGridEditor'),
    'ai-commit-generator': lazyWithRetry(() => import('@/components/AiCommitGenerator.tsx'), 'AiCommitGenerator'),
    'json-tree-navigator': lazyWithRetry(() => import('@/components/features/JsonTreeNavigator.tsx'), 'JsonTreeNavigator'),
    'xbrl-converter': lazyWithRetry(() => import('@/components/features/XbrlConverter.tsx'), 'XbrlConverter'),
    'ai-unit-test-generator': lazyWithRetry(() => import('@/components/features/AiUnitTestGenerator.tsx'), 'AiUnitTestGenerator'),
    'prompt-craft-pad': lazyWithRetry(() => import('@/components/features/PromptCraftPad.tsx'), 'PromptCraftPad'),
    'linter-formatter': lazyWithRetry(() => import('@/components/features/CodeFormatter.tsx'), 'CodeFormatter'),
    'schema-designer': lazyWithRetry(() => import('@/components/features/SchemaDesigner.tsx'), 'SchemaDesigner'),
    'pwa-manifest-editor': lazyWithRetry(() => import('@/components/features/PwaManifestEditor.tsx'), 'PwaManifestEditor'),
    'markdown-slides-generator': lazyWithRetry(() => import('@/components/features/MarkdownSlides.tsx'), 'MarkdownSlides'),
    'screenshot-to-component': lazyWithRetry(() => import('@/components/features/ScreenshotToComponent.tsx'), 'ScreenshotToComponent'),
    'digital-whiteboard': lazyWithRetry(() => import('@/components/features/DigitalWhiteboard.tsx'), 'DigitalWhiteboard'),
    'theme-designer': lazyWithRetry(() => import('@/components/features/ThemeDesigner.tsx'), 'ThemeDesigner'),
    'svg-path-editor': lazyWithRetry(() => import('@/components/features/SvgPathEditor.tsx'), 'SvgPathEditor'),
    'ai-style-transfer': lazyWithRetry(() => import('@/components/features/AiStyleTransfer.tsx'), 'AiStyleTransfer'),
    'ai-coding-challenge': lazyWithRetry(() => import('@/components/AiCodingChallenge.tsx'), 'AiCodingChallenge'),
    'typography-lab': lazyWithRetry(() => import('@/components/features/TypographyLab.tsx'), 'TypographyLab'),
    'code-review-bot': lazyWithRetry(() => import('@/components/features/CodeReviewBot.tsx'), 'CodeReviewBot'),
    'ai-pull-request-assistant': lazyWithRetry(() => import('@/components/features/AiPullRequestAssistant.tsx'), 'AiPullRequestAssistant'),
    'changelog-generator': lazyWithRetry(() => import('@/components/features/ChangelogGenerator.tsx'), 'ChangelogGenerator'),
    'cron-job-builder': lazyWithRetry(() => import('@/components/features/CronJobBuilder.tsx'), 'CronJobBuilder'),
    'ai-code-migrator': lazyWithRetry(() => import('@/components/features/AiCodeMigrator.tsx'), 'AiCodeMigrator'),
    'visual-git-tree': lazyWithRetry(() => import('@/components/features/VisualGitTree.tsx'), 'VisualGitTree'),
    'worker-thread-debugger': lazyWithRetry(() => import('@/components/features/WorkerThreadDebugger.tsx'), 'WorkerThreadDebugger'),
    'ai-image-generator': lazyWithRetry(() => import('@/components/features/AiImageGenerator.tsx'), 'AiImageGenerator'),
    'async-call-tree-viewer': lazyWithRetry(() => import('@/components/features/AsyncCallTreeViewer.tsx'), 'AsyncCallTreeViewer'),
    'audio-to-code': lazyWithRetry(() => import('@/components/features/AudioToCode.tsx'), 'AudioToCode'),
    'code-diff-ghost': lazyWithRetry(() => import('@/components/features/CodeDiffGhost.tsx'), 'CodeDiffGhost'),
    'code-spell-checker': lazyWithRetry(() => import('@/components/features/CodeSpellChecker.tsx'), 'CodeSpellChecker'),
    'color-palette-generator': lazyWithRetry(() => import('@/components/features/ColorPaletteGenerator.tsx'), 'ColorPaletteGenerator'),
    'logic-flow-builder': lazyWithRetry(() => import('@/components/features/LogicFlowBuilder.tsx'), 'LogicFlowBuilder'),
    'meta-tag-editor': lazyWithRetry(() => import('@/components/features/MetaTagEditor.tsx'), 'MetaTagEditor'),
    'network-visualizer': lazyWithRetry(() => import('@/components/features/NetworkVisualizer.tsx'), 'NetworkVisualizer'),
    'responsive-tester': lazyWithRetry(() => import('@/components/features/ResponsiveTester.tsx'), 'ResponsiveTester'),
    'sass-scss-compiler': lazyWithRetry(() => import('@/components/features/SassScssCompiler.tsx'), 'SassScssCompiler'),
    'api-mock-generator': lazyWithRetry(() => import('@/components/features/ApiMockGenerator.tsx'), 'ApiMockGenerator'),
    'env-manager': lazyWithRetry(() => import('@/components/features/EnvManager.tsx'), 'EnvManager'),
    'performance-profiler': lazyWithRetry(() => import('@/components/features/PerformanceProfiler.tsx'), 'PerformanceProfiler'),
    'a11y-auditor': lazyWithRetry(() => import('@/components/features/AccessibilityAuditor.tsx'), 'AccessibilityAuditor'),
    'ci-cd-generator': lazyWithRetry(() => import('@/components/features/CiCdPipelineGenerator.tsx'), 'CiCdPipelineGenerator'),
    'deployment-preview': lazyWithRetry(() => import('@/components/features/DeploymentPreview.tsx'), 'DeploymentPreview'),
    'security-scanner': lazyWithRetry(() => import('@/components/features/SecurityScanner.tsx'), 'SecurityScanner'),
    'terraform-generator': lazyWithRetry(() => import('@/components/features/TerraformGenerator.tsx'), 'TerraformGenerator'),
    'ai-personality-forge': lazyWithRetry(() => import('@/components/features/AiPersonalityForge.tsx'), 'AiPersonalityForge'),
    'weekly-digest-generator': lazyWithRetry(() => import('@/components/features/WeeklyDigestGenerator.tsx'), 'WeeklyDigestGenerator'),
    'one-click-refactor': lazyWithRetry(() => import('@/components/features/OneClickRefactor.tsx'), 'OneClickRefactor'),
    'bug-reproducer': lazyWithRetry(() => import('@/components/features/BugReproducer.tsx'), 'BugReproducer'),
    'tech-debt-sonar': lazyWithRetry(() => import('@/components/features/TechDebtSonar.tsx'), 'TechDebtSonar'),
    'iam-policy-generator': lazyWithRetry(() => import('@/components/features/IamPolicyGenerator.tsx'), 'IamPolicyGenerator'),
    'iam-policy-visualizer': lazyWithRetry(() => import('@/components/features/IamPolicyVisualizer.tsx'), 'IamPolicyVisualizer'),
    'gmail-addon-simulator': lazyWithRetry(() => import('@/components/features/GmailAddonSimulator.tsx'), 'GmailAddonSimulator'),
};

export const ALL_FEATURES: Feature[] = RAW_FEATURES.map(feature => ({
    ...feature,
    component: componentMap[feature.id],
}));

export const FEATURES_MAP = new Map(ALL_FEATURES.map(f => [f.id, f]));